# Generated by Django 5.2.4 on 2025-07-24 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_id', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('validade', models.DateField()),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
