# Generated by Django 5.2.1 on 2025-05-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalpartida',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
