# Generated by Django 5.2.1 on 2025-05-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_auto_20250522_1723'),
    ]

    operations = [
        # Primeiro criamos uma nova tabela temporária com os campos corretos
        migrations.CreateModel(
            name='DespesaTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_temp', to='campeonato.profissionalpartida')),
            ],
        ),
        # Removemos a tabela original
        migrations.DeleteModel(
            name='Despesa',
        ),
        # Recreamos a tabela com a estrutura correta
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='campeonato.profissionalpartida')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        # Removemos a tabela temporária
        migrations.DeleteModel(
            name='DespesaTemp',
        ),
    ]
