# Generated by Django 5.2.4 on 2025-07-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_alter_campeonato_num_classificados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='num_divisoes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
