# Generated by Django 5.2.4 on 2025-07-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_remove_required_num_divisoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalcampeonato',
            name='data_vinculacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profissionalcampeonato',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
