# Generated by Django 5.2.1 on 2025-05-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_auto_20250522_1728'),
    ]

    operations = [
    ]
