# Generated by Django 5.2.4 on 2025-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_profissionalcampeonato_data_vinculacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodada',
            options={'ordering': ['numero'], 'verbose_name': 'Rodada', 'verbose_name_plural': 'Rodadas'},
        ),
        migrations.AddField(
            model_name='rodada',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
