# Generated by Django 5.2.1 on 2025-05-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_update_despesa_migration'),
        ('campeonato', '0004_auto_20250522_1728'),
    ]

    operations = [
    ]
