# Generated by Django 5.2.1 on 2025-05-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0005_merge_20250523_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecampeonato',
            name='campo_estadio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timecampeonato',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timecampeonato',
            name='presidente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
