# Generated by Django 5.2.1 on 2025-05-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0006_timecampeonato_campo_estadio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='tipo',
        ),
    ]
