# Generated by Django 5.2.1 on 2025-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0007_remove_profissional_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('CPF', 'CPF'), ('ALEATORIA', 'Aleatória'), ('OUTRA', 'Outra')], max_length=10, null=True),
        ),
    ]
