# Generated by Django 5.2.1 on 2025-05-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0008_profissional_chave_pix_profissional_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='nao_iniciado', max_length=15),
        ),
    ]
