# Generated by Django 5.2.1 on 2025-05-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0009_campeonato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='ida_volta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='num_classificados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='num_divisoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='num_grupos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='num_turnos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='observacoes_formato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='tipo_formato',
            field=models.CharField(choices=[('liga', 'Liga'), ('mata_mata', 'Mata-mata'), ('grupos', 'Grupos'), ('misto', 'Misto'), ('divisoes', 'Divisões')], default='liga', max_length=20),
        ),
    ]
