# Generated by Django 5.2.1 on 2025-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0010_campeonato_ida_volta_campeonato_num_classificados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalcampeonato',
            name='funcao_principal',
            field=models.CharField(choices=[('ARB', 'Árbitro'), ('BAN', 'Bandeirinha'), ('MES', 'Mesário'), ('QAR', 'Quarto Árbitro'), ('OUT', 'Outras funções')], default='ARB', max_length=3, verbose_name='Função Principal'),
        ),
    ]
