# Generated by Django 5.2.1 on 2025-06-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0011_profissionalcampeonato_funcao_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='disputa_terceiro',
            field=models.BooleanField(default=False),
        ),
    ]
