# Generated by Django 5.2.1 on 2025-06-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0013_partida_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='local',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time_mandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_mandante', to='campeonato.timecampeonato'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_visitante', to='campeonato.timecampeonato'),
        ),
    ]
