# Generated by Django 5.2.1 on 2025-07-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0014_alter_partida_data_hora_alter_partida_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionalcampeonato',
            name='funcao_principal',
        ),
    ]
