# Generated by Django 5.2.1 on 2025-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0015_remove_profissionalcampeonato_funcao_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='confrontos_mesmo_grupo',
            field=models.BooleanField(default=True),
        ),
    ]
